include /usr/local/share/luggage/luggage.make

TITLE=6thFloorCombined_Creative_Studio_6501
REVERSE_DOMAIN=com.adpcph.it
PAYLOAD=unbz2-utilities-FieryDriverInstaller.app \
	pack-script-postflight
PACKAGE_VERSION=1.0.5

# 
# prepare-files: l_Library
# 	# Copy the installer to the Library
# 	@sudo mkdir -p @{WORK_D}/Library/Printers/AdPeopleC6501
# 	@sudo ${CP} -R ./fieryinstaller.app/ @{WORK_D}/Library/Printers/AdPeopleC6501/
