#!/bin/sh
# Jens Raaby
# Adpeople 
printername="Creative_6501"
location="6. sal"
gui_display_name="Creative 6501"
address="lpd://152.146.38.25"
driver_ppd="/Library/Printers/PPDs/Contents/Resources/en.lproj/Fiery X3eTY2 65_55C-KM PS v1.1 eu"

if [ $? -eq 0 ]; then
        /usr/sbin/lpadmin -x $printername
fi

# Now we can install the printer.
/usr/sbin/lpadmin \
        -p "$printername" \
        -L "$location" \
        -D "$gui_display_name" \
        -v "$address" \
        -P "$driver_ppd" \
        -o "$option_1" \
        -o "$option_2" \
        -o "$option_3" \
        -o printer-is-shared=false \
        -E

# Enable and start the printers on the system (after adding the printer initially it is paused).
/usr/sbin/cupsenable $(lpstat -p | grep -w "printer" | awk '{print$2}')

lpadmin -d $printername
exit 0
